### PR TITLE
Fix ImportError on Python2.6

### PR DESCRIPTION
**Pull request by mzabuawala**
Hi,

We were using Flask-Script-2.0.5 earlier without an issue but due to recent dependancy change to version Flask-Script-2.0.6, we are now force to use newer version which does not work with Python2.6, We need support of Python2.6 for CentOS 6.

Details:
```
    import flask_migrate
  File "/var/lib/jenkins/workspace/py_code-master-python26/py_code-venv/lib/python2.6/site-packages/flask_migrate/__init__.py", line 4, in <module>
    from flask_script import Manager
  File "/var/lib/jenkins/workspace/py_code-master-python26/py_code-venv/lib/python2.6/site-packages/flask_script/__init__.py", line 10, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
```

### CODE REVIEW

**Comment by davidism** [comment]
The package `ordereddict` is not a built-in, so this would require a new dependency, probably not what you meant to do. The solution here is to revert whatever patch added the `OrderedDict`.

<sub>But the real solution is to upgrade from Python 2.6.</sub>

**Comment by mzabuawala** [comment]
Yes, we know that `ordereddict` is not a built-in, but for Python2.6 that is available as a replacement of OrderedDict.

We can't upgrade python because it will break CentOS6.
https://superuser.com/questions/1027526/upgrade-python-from-2-6-to-2-7-on-centos-6-5

**Comment by anthraxx** [comment]
Python 2.6 is end of life since 2013 which means it doesn't even get security releases.
I fail to see why features and implementations should be downgraded to support something that literally died 4 years ago.
If 2.6 is required just because of yum, then yum should be patched. Seriously, stop using 2.6 and find a solution that migrates your environment to supported software.

**Comment by davidism** [comment]
You don't have to upgrade the system python, more than one version can live side by side.

**Comment by davidism** [comment]
Again, this can be solved without the extra package, you just need to revert whatever added the ordereddict. I'm not sure if that's worth it though. If you need Flask-Script on 2.6 you can always just keep using the previous version.

**Comment by mzabuawala** [comment]
@davidism, Yes we can install more than one version of python on a system but in case of CentOS6, other versions are not present on YUM repository, we have to compile it manually from source and that will add an overhead of maintaining a software manually for system admins so they are not happy with it :(

**Comment by mzabuawala** [comment]
Ok, I'll change the requirement.txt according.

**Comment by anthraxx** [comment]
I still strongly encourage you to migrate away from an outdated and dead system that's core is based on unsupported and vulnerable software. You should upgrade to CentOS7. The old one isn't any different from using windows XP.

**Comment by mzabuawala** [comment]
We do use CentOS 7, however we have thousands of downloads per year from CentOS 6 users, and we know that many of our customers still use RHEL 6 which is in support for a number of years yet for Enterprise users who may not be in a position to upgrade. This is extremely common in many industries in which our software is used.
