### ISSUE TITLE
0.6.1 fails to embed ipython at all

### ISSUE THREAD

**Issue by zgoda** [smurfix/flask-script#70]
Environment:
Python 2.7.5
IPython 0.13.2
flask-script 0.6 and 0.6.1

With IPython 0.13 everything works fine in flask-script 0.6, Shell command launches ipython as expected.
After upgrading to 0.6.1 Shell command launches ordinary Python shell. No errors, stack traces, just plain Python shell instead of IPython.
IPython 1.0 behaves exactly as 0.13 under 0.6.1, fails under 0.6 with AttributeError: 'module' object has no attribute 'frontend'.
