### ISSUE TITLE
Issue "unexpected keyword argument 'func_stack' - using with Flask_Assets in 2.0.5

### ISSUE THREAD

**Issue by sandipmore** [smurfix/flask-script#133]
#!/usr/bin/env python
from flask.ext.script import Manager , Shell, Server
from flask_assets import ManageAssets
from example import app,assets_env

manager = Manager(app)
manager.add_command("runserver" , Server())
manager.add_command("shell",Shell())
manager.add_command("assets", ManageAssets(assets_env))
manager.run()

I am getting following error when I used Flask_Script 2.0.5. Same thing works with Flask_script 0.5x.

Traceback (most recent call last)
  File "manage.py", line 10, in <module>
    manager.run()
  File "/Users/sandipmore/Documents/workspace/magic-chips/backend/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/sandipmore/Documents/workspace/magic-chips/backend/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 350, in handle
    app_parser = self.create_parser(prog)
  File "/Users/sandipmore/Documents/workspace/magic-chips/backend/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 193, in create_parser
    command_parser = command.create_parser(name, func_stack=func_stack, parent=self)
TypeError: create_parser() got an unexpected keyword argument 'func_stack'
