### ISSUE TITLE
0.5.3 to 0.6.x

### ISSUE THREAD

**Issue by locojay** [smurfix/flask-script#71]
after upgrading to 0.6.x i get 

```
Traceback (most recent call last):
  File "manage.py", line 119, in <module>
    manager.run()
  File "/Users/locojay/.virtualenvs/hamss/lib/python2.7/site-packages/flask_script/__init__.py", line 366, in run
    raise e
TypeError: create_parser() got an unexpected keyword argument 'parents'
```

**Comment by jeffwidman** [comment]
@techniq this issue can be closed, correct?
